"""Public SAGE-Kit API surface."""

from __future__ import annotations

__version__ = "2026.7.20.2"

from .harness import (
    CompiledPacket,
    CheckpointResult,
    CandidateAssessment,
    CandidateFingerprint,
    CandidateFreezeResult,
    ChangeClass,
    ContractSelection,
    ManagedExecutionError,
    ExecutionCounters,
    NormalizedSpec,
    PacketConfigurationError,
    PacketError,
    ProcessResult,
    ProjectCheckResult,
    PreauthorizedConvergenceAuthority,
    ResourceClass,
    SourceConfig,
    SourceConfigurationError,
    TaskEvidenceValidationResult,
    ValidationError,
    WorkspaceBinding,
    WorkspaceIdentity,
    WorkspaceVerification,
    assess_candidate,
    build_project_workspace_binding,
    check_project,
    compile_ephemeral_packet,
    clear_checkpoint,
    create_checkpoint,
    discover_project_workspace,
    freeze_candidate,
    load_project_normalized_spec,
    load_project_source_config,
    get_checkpoint_status,
    run_managed_command,
    run_managed_git_command,
    run_managed_readonly_git_command,
    resume_checkpoint,
    validate_task_and_evidence_records,
    write_ephemeral_packet,
    verify_project_workspace,
)

__all__ = [
    "__version__",
    "CompiledPacket",
    "CheckpointResult",
    "CandidateAssessment",
    "CandidateFingerprint",
    "CandidateFreezeResult",
    "ChangeClass",
    "ContractSelection",
    "ManagedExecutionError",
    "ExecutionCounters",
    "NormalizedSpec",
    "PacketConfigurationError",
    "PacketError",
    "ProcessResult",
    "ProjectCheckResult",
    "PreauthorizedConvergenceAuthority",
    "ResourceClass",
    "SourceConfig",
    "SourceConfigurationError",
    "TaskEvidenceValidationResult",
    "ValidationError",
    "WorkspaceBinding",
    "WorkspaceIdentity",
    "WorkspaceVerification",
    "assess_candidate",
    "build_project_workspace_binding",
    "check_project",
    "discover_project_workspace",
    "freeze_candidate",
    "compile_ephemeral_packet",
    "clear_checkpoint",
    "create_checkpoint",
    "load_project_normalized_spec",
    "load_project_source_config",
    "get_checkpoint_status",
    "run_managed_command",
    "run_managed_git_command",
    "run_managed_readonly_git_command",
    "resume_checkpoint",
    "validate_task_and_evidence_records",
    "verify_project_workspace",
    "write_ephemeral_packet",
]
